<thead>
    <th scope="col">Country</th>
    <th scope="col">State</th>
    <th scope="col">Country Code</th>
    <th scope="col">Phone Number</th>
</thead>
<tbody>
    <?php if(!isset($phones) || count($phones) == 0) : ?>
    <tr>
        <td colspan="5">No phone numbers found!</td>
    </tr>
    <?php else : ?>
        <?php foreach($phones as $p) : ?>
            <tr>
                <td><?= $countries[$p->getCode()]; ?></td>
                <td><?= $p->getState(); ?></td>
                <td><?= '+'.$p->getCode(); ?></td>
                <td><?= $p->getNumber(); ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</tbody>